version: "3.8"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Password1
    ports:
      - 6055:6055

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresdata:
